language: python
dist: xenial
sudo: false

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.7-dev" # 3.7 development branch
  - "3.8-dev" # 3.7 development branch
  - "nightly"

matrix:
  allow_failures:
    - python: "3.7-dev"
    - python: "3.8-dev"
    - python: "nightly"

virtualenv:
  system_site_packages: false

services:
  - postgresql

install:
  - pip install -U pip
  # only wheel
  - pip install wheel
  - pip install psycopg2
  - pip install passlib
  - pip install python-coveralls
  - pip install -U flake8 pytest pytest-cov
  - pip install WebTest
  - pip install -e .

env:
  global:
    - ANYBLOK_DATABASE_NAME=travis_ci_test
    - ANYBLOK_DATABASE_DRIVER=postgresql
    - ANYBLOK_DATABASE_USER=postgres

script:
  - flake8 anyblok_pyramid_rest_api --ignore F999
  - psql -c 'create database travis_ci_test;' -U postgres
  - py.test anyblok_pyramid_rest_api/tests

after_success:
  coveralls
